export const UPDATE_STRATEGY = {
  IS_NON_EXISTENT_NEXT_NODE: 'iS_NON_EXISTENT_NEXT_NODE',
  IS_NON_EXISTENT_PREVIOUS_NODE: 'IS_NON_EXISTENT_PREVIOUS_NODE',
  ARE_BOTH_STRING: 'ARE_BOTH_STRING',
  IS_DIFFERENT_TAG_NAME: 'IS_DIFFERENT_TAG_NAME',
} as const;
